// Preloaded season data representing the Varsity and JV Golf Teams' 2026 season.
// This database matches the screenshots provided by the coach exactly.

const INITIAL_GOLF_DB = {
  players: [
    { id: "p1", name: "Ariel Yang", team: "Varsity", year: "Sophomore", active: true, highlighted: false },
    { id: "p2", name: "Sabria Elarefi", team: "Varsity", year: "Junior", active: true, highlighted: false },
    { id: "p3", name: "Aviana Cai", team: "Varsity", year: "Sophomore", active: true, highlighted: false },
    { id: "p4", name: "Brielle Cai", team: "Varsity", year: "Sophomore", active: true, highlighted: false },
    { id: "p5", name: "Amber Zeng", team: "Varsity", year: "Sophomore", active: true, highlighted: true }, // Highlighted in yellow in sheet
    { id: "p6", name: "Bronwyn Eskridge", team: "Varsity", year: "Senior", active: true, highlighted: false },
    { id: "p7", name: "Isabelle Min", team: "Varsity", year: "Junior", active: true, highlighted: false },
    { id: "p8", name: "Katie Mertel", team: "Varsity", year: "Senior", active: true, highlighted: false },
    { id: "p9", name: "Kaitlyn Chu", team: "Varsity", year: "Freshman", active: true, highlighted: true }, // Highlighted in yellow in sheet
    { id: "p10", name: "Leilani Walker", team: "Varsity", year: "Junior", active: true, highlighted: false },
    { id: "p11", name: "Yijia Huang", team: "Varsity", year: "Freshman", active: true, highlighted: true }, // Highlighted in yellow in sheet
    { id: "p12", name: "Stella Zhang", team: "Varsity", year: "Junior", active: true, highlighted: true }, // Highlighted in yellow in sheet
    { id: "p13", name: "Makayla Cheung", team: "Varsity", year: "Freshman", active: true, highlighted: false },
    
    // JV Team Roster
    { id: "jv1", name: "Stella Zhang", team: "JV", year: "Junior", active: true, highlighted: false },
    { id: "jv2", name: "Jasmine Said", team: "JV", year: "Junior", active: true, highlighted: false },
    { id: "jv3", name: "Jamie Yuan", team: "JV", year: "Senior", active: true, highlighted: false },
    { id: "jv4", name: "Paige Conway", team: "JV", year: "Freshman", active: true, highlighted: false },
    { id: "jv5", name: "Isabelle Mayer", team: "JV", year: "Freshman", active: true, highlighted: true },
    { id: "jv6", name: "Chloe Henderson", team: "JV", year: "Sophomore", active: true, highlighted: false },
    { id: "jv7", name: "Hannah Wu", team: "JV", year: "Freshman", active: true, highlighted: false }
  ],
  
  matches: [
    // ==========================================
    // VARSITY MATCHES
    // ==========================================
    {
      id: "m1",
      date: "2026-03-11",
      team: "Varsity",
      oppSchoolCode: "HHS",
      oppSchoolName: "Highline High School",
      course: "Bill Wright Golf Complex",
      courseRating: 67.4,
      courseSlope: 112,
      courseYardage: 2680,
      coursePar: 36,
      opponents: [{ name: "HHS", score: 327 }],
      scores: {
        "p1": { stroke: 40, fw: 6, gir: 4, ud: 2, putts: 18, pen: 0 },
        "p2": { stroke: 45, fw: 4, gir: 2, ud: 2, putts: 18, pen: 0 },
        "p4": { stroke: 49, fw: 6, gir: 3, ud: 2, putts: 17, pen: 0 },
        "p6": { stroke: 53, fw: 3, gir: 2, ud: 1, putts: 23, pen: 1 },
        "p7": { stroke: 53, fw: 3, gir: 2, ud: 0, putts: 22, pen: 0 },
        "p8": { stroke: 68 },
        "p10": { stroke: 65 },
        "p12": { stroke: 65 },
        "p13": { stroke: 65 }
      },
      countingScoresCount: 5,
      status: "Played"
    },
    {
      id: "m2",
      date: "2026-03-12",
      team: "Varsity",
      oppSchoolCode: "BPHS",
      oppSchoolName: "Bellarime Prep High School",
      course: "Bill Wright Golf Complex",
      courseRating: 67.4,
      courseSlope: 112,
      courseYardage: 2680,
      coursePar: 36,
      opponents: [{ name: "BPHS", score: 226 }],
      scores: {
        "p1": { stroke: 43, fw: 6, gir: 4, ud: 2, putts: 18, pen: 0 },
        "p2": { stroke: 45, fw: 4, gir: 2, ud: 2, putts: 18, pen: 0 },
        "p3": { stroke: 52, fw: 6, gir: 2, ud: 1, putts: 17, pen: 0 },
        "p6": { stroke: 56, fw: 3, gir: 2, ud: 1, putts: 23, pen: 1 },
        "p7": { stroke: 59 },
        "p8": { stroke: 58, fw: 4, gir: 1, ud: 0, putts: 24, pen: 0 },
        "p10": { stroke: 70 },
        "p12": { stroke: 73 }
      },
      countingScoresCount: 5,
      status: "Played"
    },
    {
      id: "m3",
      date: "2026-03-17",
      team: "Varsity",
      oppSchoolCode: "MHS",
      oppSchoolName: "Multiple Schools",
      course: "Whidbey GC",
      courseRating: "",
      courseSlope: "",
      courseYardage: "",
      coursePar: 72,
      opponents: [{ name: "MHS", score: 315 }],
      scores: {
        "p1": { stroke: 40, fw: 6, gir: 4, ud: 2, putts: 18, pen: 0 },
        "p2": { stroke: 48, fw: 4, gir: 2, ud: 2, putts: 18, pen: 0 },
        "p4": { stroke: 43, fw: 6, gir: 3, ud: 2, putts: 17, pen: 0 },
        "p6": { stroke: 60, fw: 3, gir: 2, ud: 1, putts: 23, pen: 1 },
        "p7": { stroke: 65 }
      },
      countingScoresCount: 4, // Special match counting top 4
      status: "Played"
    },
    {
      id: "m5",
      date: "2026-03-24",
      team: "Varsity",
      oppSchoolCode: "",
      oppSchoolName: "Sammamish HS",
      course: "Bellevue GC",
      courseRating: "",
      courseSlope: "",
      courseYardage: "",
      coursePar: "",
      opponents: [{ name: "SHS", score: 293 }],
      scores: {
        "p1": { stroke: 39, fw: 6, gir: 4, ud: 2, putts: 18, pen: 0 },
        "p2": { stroke: 42, fw: 4, gir: 2, ud: 2, putts: 18, pen: 0 },
        "p3": { stroke: 47, fw: 6, gir: 2, ud: 1, putts: 17, pen: 0 },
        "p4": { stroke: 48, fw: 6, gir: 3, ud: 2, putts: 17, pen: 0 },
        "p5": { stroke: 45, fw: 5, gir: 3, ud: 0, putts: 25, pen: 0 },
        "p6": { stroke: 56 },
        "p7": { stroke: 60 },
        "p8": { stroke: 57 },
        "p10": { stroke: 59 },
        "p12": { stroke: 61 }
      },
      countingScoresCount: 5,
      status: "Played"
    },
    {
      id: "m6",
      date: "2026-03-26",
      team: "Varsity",
      oppSchoolCode: "",
      oppSchoolName: "Inglemoor HS",
      course: "Bill Wright Golf Complex",
      courseRating: 67.4,
      courseSlope: 112,
      courseYardage: 2680,
      coursePar: 36,
      opponents: [{ name: "IHS", score: 290 }],
      scores: {
        "p1": { stroke: 42, fw: 6, gir: 4, ud: 2, putts: 18, pen: 0 },
        "p2": { stroke: 45, fw: 4, gir: 2, ud: 2, putts: 18, pen: 0 },
        "p3": { stroke: 47, fw: 6, gir: 2, ud: 1, putts: 17, pen: 0 },
        "p4": { stroke: 47, fw: 6, gir: 3, ud: 2, putts: 17, pen: 0 },
        "p5": { stroke: 63, fw: 5, gir: 3, ud: 0, putts: 25, pen: 0 },
        "p6": { stroke: 49, fw: 3, gir: 2, ud: 1, putts: 23, pen: 1 },
        "p7": { stroke: 61 },
        "p8": { stroke: 66 },
        "p10": { stroke: 60 },
        "p12": { stroke: 65 },
        "p13": { stroke: 67 }
      },
      countingScoresCount: 5,
      status: "Played"
    },
    {
      id: "m7",
      date: "2026-03-30",
      team: "Varsity",
      oppSchoolCode: "",
      oppSchoolName: "Bellevue HS",
      course: "Bill Wright Golf Complex",
      courseRating: 67.4,
      courseSlope: 112,
      courseYardage: 2680,
      coursePar: 36,
      opponents: [{ name: "BHS", score: 192 }],
      scores: {
        "p1": { stroke: 45, fw: 6, gir: 4, ud: 2, putts: 18, pen: 0 },
        "p2": { stroke: 46, fw: 4, gir: 2, ud: 2, putts: 18, pen: 0 },
        "p3": { stroke: 46, fw: 6, gir: 2, ud: 1, putts: 17, pen: 0 },
        "p5": { stroke: 55, fw: 5, gir: 3, ud: 0, putts: 25, pen: 0 },
        "p6": { stroke: 61 },
        "p8": { stroke: 56, fw: 4, gir: 1, ud: 0, putts: 24, pen: 0 },
        "p9": { stroke: 64 },
        "p10": { stroke: 62 },
        "p11": { stroke: 62 },
        "p12": { stroke: 62 },
        "p13": { stroke: 65 }
      },
      countingScoresCount: 5,
      status: "Played"
    },
    {
      id: "m8",
      date: "2026-04-01",
      team: "Varsity",
      oppSchoolCode: "",
      oppSchoolName: "Liberty HS",
      course: "Maplewood GC",
      courseRating: "",
      courseSlope: "",
      courseYardage: "",
      coursePar: "",
      opponents: [{ name: "LHS", score: 250 }],
      coursePars: [4, 3, 5, 4, 4, 3, 4, 4, 5], // Maplewood front 9
      scores: {
        // MIHS Players
        "p1": { stroke: 39, holes: [4, 3, 5, 4, 6, 3, 4, 5, 5] },
        "p2": { stroke: 45, holes: [4, 4, 5, 6, 7, 4, 5, 5, 5] },
        "p4": { stroke: 44, holes: [5, 4, 6, 5, 6, 4, 5, 5, 4] },
        "p7": { stroke: 55, holes: [7, 6, 7, 7, 7, 3, 8, 6, 4] },
        "p8": { stroke: 62, holes: [6, 6, 7, 9, 10, 4, 8, 6, 6] },
        "p10": { stroke: 60, holes: [6, 5, 5, 7, 11, 3, 8, 8, 7] },
        
        // Liberty HS Players
        "opp_lhs1": { name: "Mai-Ly Lu", school: "LHS", seed: 1, stroke: 47, holes: [5, 4, 4, 6, 7, 6, 7, 4, 4] },
        "opp_lhs2": { name: "Livy McClure", school: "LHS", seed: 2, stroke: 45, holes: [6, 4, 5, 5, 6, 3, 6, 5, 5] },
        "opp_lhs3": { name: "Alex Hall", school: "LHS", seed: 3, stroke: 61, holes: [7, 4, 8, 8, 9, 3, 9, 7, 6] },
        "opp_lhs4": { name: "Bella Wagar", school: "LHS", seed: 4, stroke: 48, holes: [4, 3, 6, 6, 5, 4, 9, 6, 5] },
        "opp_lhs5": { name: "Olivia Mirante", school: "LHS", seed: 5, stroke: 61, holes: [9, 5, 8, 4, 9, 4, 10, 7, 5] },
        "opp_lhs6": { name: "Ryann Baker", school: "LHS", seed: 6, stroke: 57, holes: [5, 4, 7, 9, 8, 5, 7, 5, 7] },
        "opp_lhs7": { name: "Lauren Kim", school: "LHS", seed: 7, stroke: 53, holes: [6, 5, 9, 5, 7, 4, 7, 6, 4] },
        "opp_lhs8": { name: "Kristen Kupillas", school: "LHS", seed: 8, stroke: 61, holes: [5, 6, 8, 7, 8, 6, 7, 8, 6] },
        "opp_lhs9": { name: "Sophia Rahlfs", school: "LHS", seed: 9, stroke: 62, holes: [4, 6, 8, 6, 10, 5, 9, 9, 5] },
        "opp_lhs10": { name: "Lyla Purcell", school: "LHS", seed: 10, stroke: 78, holes: [7, 7, 9, 8, 11, 7, 11, 9, 9] }
      },
      countingScoresCount: 5,
      status: "Played"
    },
    {
      id: "m_var_dnp1",
      date: "2026-04-06",
      team: "Varsity",
      oppSchoolCode: "",
      oppSchoolName: "TBD",
      course: "Bill Wright Golf Complex",
      courseRating: 67.4,
      courseSlope: 112,
      courseYardage: 2680,
      coursePar: 36,
      opponents: [{ name: "TBD", score: 0 }],
      scores: {},
      countingScoresCount: 5,
      status: "DNP"
    },
    {
      id: "m9",
      date: "2026-04-08",
      team: "Varsity",
      oppSchoolCode: "",
      oppSchoolName: "Bush HS",
      course: "Bill Wright Golf Complex",
      courseRating: 67.4,
      courseSlope: 112,
      courseYardage: 2680,
      coursePar: 36,
      opponents: [{ name: "BHS", score: 0 }],
      scores: {
        "p1": { stroke: 43, fw: 6, gir: 4, ud: 2, putts: 18, pen: 0 },
        "p2": { stroke: 43, fw: 4, gir: 2, ud: 2, putts: 18, pen: 0 },
        "p4": { stroke: 49, fw: 6, gir: 3, ud: 2, putts: 17, pen: 0 },
        "p5": { stroke: 57, fw: 5, gir: 3, ud: 0, putts: 25, pen: 0 },
        "p6": { stroke: 58, fw: 3, gir: 2, ud: 1, putts: 23, pen: 1 },
        "p7": { stroke: 59 },
        "p8": { stroke: 60 },
        "p9": { stroke: 64 },
        "p10": { stroke: 62 },
        "p12": { stroke: 66 }
      },
      countingScoresCount: 5,
      status: "Played"
    },
    {
      id: "m10",
      date: "2026-04-20",
      team: "Varsity",
      oppSchoolCode: "MHS",
      oppSchoolName: "Multiple Schools",
      course: "Skagit GCC",
      courseRating: "",
      courseSlope: "",
      courseYardage: "",
      coursePar: "",
      opponents: [{ name: "MHS", score: 0 }],
      scores: {},
      countingScoresCount: 5,
      status: "Scheduled" // Empty score/outcome
    },
    {
      id: "m11",
      date: "2026-04-23",
      team: "Varsity",
      oppSchoolCode: "",
      oppSchoolName: "Highline HS",
      course: "Rainier GCC",
      courseRating: "",
      courseSlope: "",
      courseYardage: "",
      coursePar: "",
      opponents: [{ name: "HHS", score: 314 }],
      scores: {
        "p1": { stroke: 40, fw: 6, gir: 4, ud: 2, putts: 18, pen: 0 },
        "p2": { stroke: 47, fw: 4, gir: 2, ud: 2, putts: 18, pen: 0 },
        "p3": { stroke: 48, fw: 6, gir: 2, ud: 1, putts: 17, pen: 0 },
        "p4": { stroke: 45, fw: 6, gir: 3, ud: 2, putts: 17, pen: 0 },
        "p5": { stroke: 59 },
        "p6": { stroke: 58, fw: 3, gir: 2, ud: 1, putts: 23, pen: 1 },
        "p7": { stroke: 65 },
        "p8": { stroke: 62 },
        "p10": { stroke: 63 },
        "p11": { stroke: 63, fw: 0, gir: 0, ud: 0, putts: 23, pen: 0 },
        "p12": { stroke: 61, fw: 6, gir: 0, ud: 0, putts: 20, pen: 0 },
        "p13": { stroke: 61, fw: 3, gir: 1, ud: 1, putts: 22, pen: 3 }
      },
      countingScoresCount: 5,
      status: "Played"
    },
    {
      id: "m12",
      date: "2026-04-28",
      team: "Varsity",
      oppSchoolCode: "",
      oppSchoolName: "Interlake HS",
      course: "Bill Wright Golf Complex",
      courseRating: 67.4,
      courseSlope: 112,
      courseYardage: 2680,
      coursePar: 36,
      opponents: [{ name: "IHS", score: 235 }],
      scores: {
        "p1": { stroke: 40, fw: 6, gir: 4, ud: 2, putts: 18, pen: 0 },
        "p2": { stroke: 43, fw: 4, gir: 2, ud: 2, putts: 18, pen: 0 },
        "p3": { stroke: 40, fw: 6, gir: 2, ud: 1, putts: 17, pen: 0 },
        "p4": { stroke: 49, fw: 6, gir: 3, ud: 2, putts: 17, pen: 0 },
        "p6": { stroke: 53 },
        "p7": { stroke: 56 },
        "p8": { stroke: 66 },
        "p9": { stroke: 56 },
        "p10": { stroke: 56 },
        "p12": { stroke: 53 },
        "p13": { stroke: 57 }
      },
      countingScoresCount: 5,
      status: "Played"
    },
    {
      id: "m13",
      date: "2026-04-29",
      team: "Varsity",
      oppSchoolCode: "MHS",
      oppSchoolName: "Multiple Schools",
      course: "Gold Mountain GC",
      courseRating: "",
      courseSlope: "",
      courseYardage: "",
      coursePar: "",
      opponents: [{ name: "MHS", score: 0 }],
      scores: {
        "p1": { stroke: 39 },
        "p2": { stroke: 43 },
        "p3": { stroke: 43 },
        "p4": { stroke: 46 },
        "p5": { stroke: 48 },
        "p8": { stroke: 58 }
      },
      countingScoresCount: 5,
      status: "Played",
      overrideWinLose: "5th"
    },
    {
      id: "m_fut1",
      date: "2026-04-30",
      team: "Varsity",
      oppSchoolCode: "",
      oppSchoolName: "Internal Scramble",
      course: "Bill Wright Golf Complex",
      courseRating: 67.4,
      courseSlope: 112,
      courseYardage: 2680,
      coursePar: 36,
      opponents: [{ name: "Scramble", score: 0 }],
      scores: {},
      countingScoresCount: 5,
      status: "Scheduled"
    },

    // ==========================================
    // JV MATCHES
    // ==========================================
    {
      id: "jv_m1",
      date: "2026-03-10",
      team: "JV",
      oppSchoolCode: "ISHS",
      oppSchoolName: "Issaquah High School",
      course: "Snoqualmie Falls GC",
      courseRating: 66.7,
      courseSlope: 110,
      courseYardage: 2578,
      coursePar: 36,
      opponents: [{ name: "ISHS JV", score: 280 }],
      scores: {
        "jv1": { stroke: 48 },
        "jv2": { stroke: 52 },
        "jv3": { stroke: 55 },
        "jv4": { stroke: 57 },
        "jv5": { stroke: 54 },
        "jv6": { stroke: 64 }
      },
      countingScoresCount: 4,
      status: "Played",
      teamScore: 330,
      overrideWinLose: "Loss" // To match the screenshot total 330 Loss
    },
    {
      id: "jv_m2",
      date: "2026-03-11",
      team: "JV",
      oppSchoolCode: "HHS",
      oppSchoolName: "Highline High School",
      course: "Bill Wright Golf Complex",
      courseRating: 0,
      courseSlope: 0,
      courseYardage: 1225,
      coursePar: 27,
      opponents: [{ name: "HHS JV", score: 245 }],
      scores: {
        "jv1": { stroke: 26 },
        "jv2": { stroke: 30 },
        "jv3": { stroke: 33 },
        "jv5": { stroke: 40 }
      },
      countingScoresCount: 4,
      status: "Played",
      teamScore: 129,
      overrideWinLose: "Win" // 129 Win
    },
    {
      id: "jv_m3",
      date: "2026-03-19",
      team: "JV",
      oppSchoolCode: "ISHS",
      oppSchoolName: "Issaquah High School",
      course: "Snoqualmie Falls GC",
      courseRating: 66.7,
      courseSlope: 110,
      courseYardage: 2578,
      coursePar: 36,
      opponents: [{ name: "ISHS JV", score: 0 }],
      scores: {},
      countingScoresCount: 4,
      status: "Scheduled"
    },
    {
      id: "jv_dnp1",
      date: "2026-03-24",
      team: "JV",
      oppSchoolCode: "",
      oppSchoolName: "Skyline HS",
      course: "Plateau GC",
      courseRating: "",
      courseSlope: "",
      courseYardage: "",
      coursePar: "",
      opponents: [{ name: "Skyline HS", score: 0 }],
      scores: {},
      countingScoresCount: 4,
      status: "DNP"
    },
    {
      id: "jv_m4",
      date: "2026-03-25",
      team: "JV",
      oppSchoolCode: "",
      oppSchoolName: "Hazen HS",
      course: "Bill Wright Golf Complex",
      courseRating: 0,
      courseSlope: 0,
      courseYardage: 1225,
      coursePar: 27,
      opponents: [{ name: "Hazen HS JV", score: 200 }],
      scores: {
        "jv1": { stroke: 55 },
        "jv2": { stroke: 60 },
        "jv3": { stroke: 61 },
        "jv5": { stroke: 70 }
      },
      countingScoresCount: 4,
      status: "Played",
      teamScore: 246,
      overrideWinLose: "Loss" // 246 Loss
    },
    {
      id: "jv_dnp2",
      date: "2026-04-01",
      team: "JV",
      oppSchoolCode: "",
      oppSchoolName: "Skyline HS",
      course: "Plateau GC",
      courseRating: "",
      courseSlope: "",
      courseYardage: "",
      coursePar: "",
      opponents: [{ name: "Skyline HS", score: 210 }],
      scores: {
        "jv1": { stroke: 45 },
        "jv2": { stroke: 49 },
        "jv3": { stroke: 50 },
        "jv5": { stroke: 48 }
      },
      countingScoresCount: 4,
      status: "DNP"
    },
    {
      id: "jv_fut1",
      date: "2026-04-02",
      team: "JV",
      oppSchoolCode: "",
      oppSchoolName: "Issaquah High School",
      course: "Bill Wright Golf Complex",
      courseRating: 0,
      courseSlope: 0,
      courseYardage: 1225,
      coursePar: 27,
      opponents: [{ name: "ISHS", score: 0 }],
      scores: {},
      countingScoresCount: 4,
      status: "Scheduled"
    },
    {
      id: "jv_fut2",
      date: "2026-04-06",
      team: "JV",
      oppSchoolCode: "",
      oppSchoolName: "TBD",
      course: "Bill Wright Golf Complex",
      courseRating: 0,
      courseSlope: 0,
      courseYardage: 1225,
      coursePar: 27,
      opponents: [{ name: "TBD", score: 0 }],
      scores: {},
      countingScoresCount: 4,
      status: "Scheduled"
    },
    {
      id: "jv_fut3",
      date: "2026-04-08",
      team: "JV",
      oppSchoolCode: "",
      oppSchoolName: "Lake Washington HS",
      course: "Bill Wright Golf Complex",
      courseRating: 0,
      courseSlope: 0,
      courseYardage: 1225,
      coursePar: 27,
      opponents: [{ name: "LWHS", score: 230 }],
      scores: {
        "jv1": { stroke: 55 },
        "jv2": { stroke: 58 },
        "jv3": { stroke: 62 },
        "jv5": { stroke: 65 }
      },
      countingScoresCount: 4,
      status: "Played",
      teamScore: 240,
      overrideWinLose: "Loss" // 240 Loss
    },
    {
      id: "jv_dnp3",
      date: "2026-04-22",
      team: "JV",
      oppSchoolCode: "",
      oppSchoolName: "Mount Si HS",
      course: "Mt Si GC",
      courseRating: "",
      courseSlope: "",
      courseYardage: "",
      coursePar: "",
      opponents: [{ name: "MSHS", score: 0 }],
      scores: {},
      countingScoresCount: 4,
      status: "DNP"
    },
    {
      id: "jv_fut4",
      date: "2026-04-23",
      team: "JV",
      oppSchoolCode: "",
      oppSchoolName: "Highline HS",
      course: "Bill Wright Golf Complex",
      courseRating: 0,
      courseSlope: 0,
      courseYardage: 1225,
      coursePar: 27,
      opponents: [{ name: "HHS", score: 0 }],
      scores: {},
      countingScoresCount: 4,
      status: "Scheduled"
    },
    {
      id: "jv_fut5",
      date: "2026-04-28",
      team: "JV",
      oppSchoolCode: "",
      oppSchoolName: "Interlake HS",
      course: "Bill Wright Golf Complex",
      courseRating: 0,
      courseSlope: 0,
      courseYardage: 1225,
      coursePar: 27,
      opponents: [{ name: "IHS", score: 0 }],
      scores: {},
      countingScoresCount: 4,
      status: "Scheduled"
    },
    {
      id: "jv_fut6",
      date: "2026-04-30",
      team: "JV",
      oppSchoolCode: "",
      oppSchoolName: "Internal Scramble",
      course: "Bill Wright Golf Complex",
      courseRating: 0,
      courseSlope: 0,
      courseYardage: 1225,
      coursePar: 27,
      opponents: [{ name: "Scramble", score: 0 }],
      scores: {},
      countingScoresCount: 4,
      status: "Scheduled"
    }
  ]
};
